name: Build airports world lite

on:
  workflow_dispatch:
  schedule:
    - cron: "18 4 * * 1"

permissions:
  contents: write

jobs:
  build-airports-world-lite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run world airports build
        run: node scripts/build-airports-world-lite.mjs

      - name: Commit generated file
        run: |
          if git diff --quiet public/data/airports-world-lite.json; then
            echo "Aucun changement à commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add public/data/airports-world-lite.json
          git commit -m "build: update airports-world-lite.json"
          git push
